### ISSUE TITLE
CarPlay: playback does not start

### ISSUE THREAD

**Issue by ivangrimaldi** [AudioBooth/AudioBooth#50]
## Description
I can't start playback from CarPlay, I can do it only if I open app on the phone and click play. After that it works but the playback progress I see in CarPlay is different from the one I see in the app on the phone (always full chapter already listened/progress bar full instead of real progress)

## Steps to Reproduce
1. Switch on the car
2. Open AudioBooth on CarPlay
3. Select book and click play
4. Empty/gray player is shown. Playback won't start. It I'll start only opening the app on the phone

## Expected Behavior
Playback can start from CarPlay 

## Actual Behavior
Playback does not start from CarPlay 

## Device Information
- **Platform:** iPhone 
- **Device Model:** iPhone SE
- **OS Version:**  iOS 26.1
- **AudioBooth Version:** 1.4
- **Audiobookshelf Server Version:** 2.32.1

## Screenshot
![image](https://github.com/user-attachments/assets/4ed094b9-9f93-4438-9eb3-3e215e08ec7d)

## Additional Context
If app was still alive between 2 car switch on and off, the playback starts auotomously as expected with also correct progress info. If instead the app was closed, then I open it in CarPlay and select the book I want to continue (or any book in general) the bug I mentioned happens

**Comment by danst83** [comment]
I’m experiencing the same issue. Sometimes I can start it from CarPlay if I’ve recently played the book on my phone, but if it’s been a while, it won’t start. I have to play it on my phone first.

**Comment by jeremygrenier** [comment]
@ivangrimaldi @danst83 Can you give it a try on [beta 1.5 (1767064550)](https://testflight.apple.com/join/cAG6dVeN)?

**Comment by ivangrimaldi** [comment]
Just tested, some news: it auto starts if app is open on phone. If app is closed and I open it from CarPlay it has the bug reported, grey screen not playing

**Comment by jeremygrenier** [comment]
@ivangrimaldi can you give another try on the latest [beta 1.5 (1767121683)](https://testflight.apple.com/join/cAG6dVeN)?

**Comment by ivangrimaldi** [comment]
Just tried same behavior. Thank you anyway!

**Comment by jeremygrenier** [comment]
@ivangrimaldi the latest [beta 1.5 (1767223694)](https://testflight.apple.com/join/cAG6dVeN)  should fix the issue if you can give it a try.

**Comment by ivangrimaldi** [comment]
I still experience the big with latest beta I downloaded,
If for instancw I am play ing sometn on Spotify, then I open AudioBooth and try to start another book, I am stick in the situation I descriver before.

Beta version tested: Version 1.5 (1767315604)

**Comment by jeremygrenier** [comment]
@ivangrimaldi can you try it on **1.5 (1767485723)**? I adjusted the logic to start playing when you select a book to align with what Audiobooks and Audible apps are doing. It should also solve your issue.

**Comment by ivangrimaldi** [comment]
Yes I confirm it's fixed!
Thanks a lot
